# This rule is not used by the project postgresql-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over database.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-admin-role
rules:
- apiGroups:
  - database.my.domain
  resources:
  - postgresqls
  verbs:
  - '*'
- apiGroups:
  - database.my.domain
  resources:
  - postgresqls/status
  verbs:
  - get
