# This rule is not used by the project postgresql-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to database.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgresql-viewer-role
rules:
- apiGroups:
  - database.my.domain
  resources:
  - postgresqls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - database.my.domain
  resources:
  - postgresqls/status
  verbs:
  - get
